# The URL the site will be built for
base_url = "https://mwillsey.com"

compile_sass = true
highlight_code = false
build_search_index = false

title = "Max Willsey"

[extra]
# Put all your custom variables here
